### ISSUE TITLE
memZono - modify to more unified set operations

### ISSUE THREAD

**Issue by jonaswagner2826** [Applied-Systems-Lab/zonoLAB#14]
Discuss:
- [ ] arguments block replacement... overloading vs varargin{} for everything... or arguments block w/ checks outside

TODO:
- [x] Create affine() <= linMap,minSum,vecSum all unified...
- [x] Create intersect() <= cartProd,labeledIntersection
- [x] overloading operations/specific functions to call affine/intersect
- [x] Add a helper function to return a cell array of keys (separate functions for dims, factors, cons) that start with a string pattern... maybe like Z.dimKeysStartsWith('x_') and Z.constraintKeysStartsWith(...) and Z.factorKeyStartsWith(...)

**Comment by jonaswagner2826** [comment]
![20240201_150706.jpg](https://github.com/Applied-Systems-Lab/zonoLAB/assets/47377464/08486293-bb36-4b0d-bf13-1ed05551d2e1)

**Comment by jonaswagner2826** [comment]
@jruths 
I'm not sold on this syntax yet (I'd much prefer:
> obj1.affine(obj2, M, 'inDims', {'x_1','x_2'}, 'outDims', {'x_3, 'x_4'})
) but here's the current affine syntax...
![Image](https://github.com/Applied-Systems-Lab/zonoLAB/assets/47377464/c97ee99d-15e4-42aa-8297-9eb66e87cc2d)

I'm using
> affine(obj,in1,in2,options)
 w/ an arguments block for the defaulting of null but I think I could switch to a varargin-based one... I'm just not sure how to do the inDims/outDims varargin logic

**Comment by jruths** [comment]
I'm ok with `obj1.affine(obj2,M, {'x_1',...,'x_n'}, {'y_1',...,'y_n'})`

Since the in/out new/old labels really go with the matrix multiplication, I can see the value in having it last.  I just don't like the 'inDims' and 'outDims' - the labeled arguments.

So these have acceptable syntax:
```
Z.affine(M)
Z.affine(M,{cell}, {cell})
Z.affine(b)
Z.affine(b,M)
Z.affine(b,M,{cell}, {cell})
Z.affine(Y)
Z.affine(Y,M)
Z.affine(Y,M,{cell}, {cell})
```

**Comment by jonaswagner2826** [comment]
@jruths 
The selection of `obj1.affine(obj2,M,{cell},{cell})` would end up being more like:

> Z.affine([],M)
> Z.affine([],M,{cell}, {cell})
> Z.affine(b)
> Z.affine(b,M)
> Z.affine(b,M,{cell}, {cell})
> Z.affine(Y)
> Z.affine(Y,M)
> Z.affine(Y,M,{cell}, {cell})

which I think wouldn't be great for standard usage when doing a mapping (but we could have the helper map function instead).

I'm fine eliminating the 'inDims'/'outDims', but I do wonder if we want 'all'/: or []/{} to represent all the dims in or if we want to just assume all dims if only one set of cell's are provided?

**Comment by jonaswagner2826** [comment]
Additional clarrification about need for the empty [] to be passed in:
- Our check to determine between M and b was if it was a vector; however, M could also be a n x 1 matrix (this was an issue I ran into and finally found)

**Comment by jonaswagner2826** [comment]
@jruths 
I previously debuged the unified commands using the basic reachability example.

I have since created a version of the NN code with the unified operations and it runs (after some fixing to the inDims/outDims code) but I'm not certain what the result is supposed to be... is this correct?:

![Image](https://github.com/Applied-Systems-Lab/zonoLAB/assets/47377464/285a6134-ce4f-4a28-9d9d-3cd335edfb0a)

![Image](https://github.com/Applied-Systems-Lab/zonoLAB/assets/47377464/33127bf3-ce16-4a07-a821-c8496bf31122)

**Comment by jruths** [comment]
Awesome!  This is looking great!  

I agree we likely want to come up with other names for these functions since they don't do the usual operation... I'll think about what that might be....

It seems like SLAM is working ok.  The neural net should look like the sinusoidal surface of the actual function... so there is some issue with that example... I haven't sat down and thought through it suuuuper carefully, but it does seem like your edits to the example are correct, so I need to check it more closely.... otherwise maybe there is some hybzono specific issue (since SLAM is working)?

**Comment by jonaswagner2826** [comment]
Merged the unified branch into main... still have to go through and update comments in the memZono code and examples

**Comment by jonaswagner2826** [comment]
@jruths 
I went back and finished the documentation/comments in the rest of memZono as requested.
I did finish a few check TODOs that you left in there (mainly just a ismember() check on if dim constraints existing already and checking of inDims) so I'm going to wait to merge it till we talk (even though it isn't much of a change)
