### ISSUE TITLE
Fix for update with unique factors/constraints but not labeled dimensions

### ISSUE THREAD

**Issue by jonaswagner2826** [Applied-Systems-Lab/zonoLAB#18]

**Comment by jonaswagner2826** [comment]
@jruths As of now the setup added a directSum() method in memZono which ignores dimensional awareness and does a direct sum (assuming correct dimensional size) and then keeps the dimensional labels of the first memZono... worth disscussion if desired in the future, but it seems to work alright (and doesn't appear to directly impact any of the other examples currently)

**Comment by jruths** [comment]
Yeahhhhhhhh.... you're going to have to convince me that this is a good idea.  I think we need to buy in completely on the dimension labels if we are really going to use them.  This feels like a cheat.

**Comment by jonaswagner2826** [comment]
Different approach:
use  .copy() ... able to specify new dimKeys... and then still use combine instead of directSum.. plus returns to overloading combine()
