### ISSUE TITLE
error with subref and memZono

### ISSUE THREAD

**Issue by JChenUTD** [Applied-Systems-Lab/zonoLAB#42]
Z( NN({'x_L0_u_1'  'x_L0_u_2'  'y_1'}) )
Unrecognized function or variable 'Z'.

Should return a hybzono obj, Jonas knows!

**Comment by jonaswagner2826** [comment]
Note:
The issue is more with how
NN({.... keys...}).Z doesn't export Z
The versions that provide correct result are:
NN.projection({...keys...}).Z
projection(NN,{...keys...}).Z
temp = NN({...keys...}); temp.Z

The issue is w/in subsref but requires more investigation to fix to call it correctly.
