### ISSUE TITLE
Fix hybzono issues w/ projection

### ISSUE THREAD

**Issue by jonaswagner2826** [Applied-Systems-Lab/zonoLAB#6]
Fix the usage issues w/ hybzono. The vset boolean issue and any other typos.

**Comment by jonaswagner2826** [comment]
@jruths this is the issue/task I made to fix things... would you like to confirm that it works for your purposes before I commit to main.

**Comment by jruths** [comment]
@jonaswagner2826 I think you can just go ahead and commit to main and I'll pull it from there to test further.  Thanks!
